-- vim.cmd([[
--   highlight BufferLineBackground none
--   highlight StatusLine none
--   highlight Normal guibg=none
--   highlight NonText guibg=none
--   highlight Normal ctermbg=none
--   highlight NonText ctermbg=none
-- ]])
